package fes.aragon.controlador;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;

import java.net.URL;
import java.util.ResourceBundle;

import fes.aragon.modelo.Clientes;
import fes.aragon.modelo.Facturas;
import fes.aragon.mysql.Conexion;
import javafx.event.ActionEvent;

import javafx.scene.control.DatePicker;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class ModificarFacturaVDController implements Initializable {
	@FXML
	private TextField txtReferrenciaFacturaVD;
	@FXML
	private DatePicker txtFechaNuevaFactVD;
	@FXML
	private TextField txtNombreFactVD;
	@FXML
	private TextField txtApellidoFactVD;
	@FXML
	private TextField txtClienteBuscar;

	@FXML
	private Button btnBuscar;
	
	@FXML
	private TableView<Clientes> tblTablaCliente;
	@FXML
	private TableColumn<Clientes, Integer> clienteID;
	@FXML
	private TableColumn<Clientes, String> clienteNombre;
	@FXML
	private TableColumn<Clientes, String> clienteApellidoPa;

	private Facturas factura = new Facturas();
	 Clientes cliente = new Clientes();

	// Event Listener on Button[#btnBuscar].onAction
	@FXML
	public void buscarCliente(ActionEvent event) {
		// TODO Autogenerated
			try {
				Conexion cnn = new Conexion();
				this.tblTablaCliente.getItems().clear();
				this.tblTablaCliente.setItems(cnn.buscarClientes(this.txtClienteBuscar.getText()));
				
			} catch (Exception e) {
				Alert alert = new Alert(Alert.AlertType.INFORMATION);
				alert.setHeaderText("Error al buscar el cliente");
				alert.setContentText("El cliente no existe");
				alert.showAndWait();
				e.printStackTrace();
			}
		}
	
	// Event Listener on Button.onAction
	@FXML
	public void accionGuardarFactVD(ActionEvent event) {
		// TODO Autogenerated

		try {
			Conexion cnn = new Conexion();
			Alert alerta = new Alert(Alert.AlertType.INFORMATION);
			Clientes cl=this.tblTablaCliente.getSelectionModel().getSelectedItem();
			if(cl!=null) {
			factura.getCliente().setIdC(cl.getIdC());
			}
			factura.setReferencia(txtReferrenciaFacturaVD.getText());
			factura.setFecha(txtFechaNuevaFactVD.getValue());
			cnn.modificarFacturas(factura);
			alerta.setHeaderText("Factura Modificada");
			alerta.setContentText("La factura se modifico correctamente");
			alerta.showAndWait();
		} catch (Exception e) {
			Alert alerta = new Alert(Alert.AlertType.INFORMATION);
			alerta.setHeaderText("Error al guardar los datos");
			alerta.setContentText("Revisa los datos o que no sean datos Invalidos");
			alerta.showAndWait();
			e.printStackTrace();
		}

	}

	// Event Listener on Button.onAction
	@FXML
	public void accionLimpiarFactVD(ActionEvent event) {
		// TODO Autogenerated
		this.limpiar();
	}

	public void modificarFacturas(Facturas factura) {
		this.factura = factura;
		this.txtNombreFactVD.setText(factura.getCliente().getNombre());
		this.txtApellidoFactVD.setText(factura.getCliente().getApellidoPaterno());
		this.txtReferrenciaFacturaVD.setText(factura.getReferencia());
		this.txtFechaNuevaFactVD.setValue(factura.getFecha());

	}
	
	// TABLA CLIENTES
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		this.clienteID.setCellValueFactory(new PropertyValueFactory<>("id"));
		this.clienteNombre.setCellValueFactory(new PropertyValueFactory<>("nombre"));
		this.clienteApellidoPa.setCellValueFactory(new PropertyValueFactory<>("apellidoPaterno"));

		this.tblTablaCliente.getSelectionModel().selectedItemProperty()
				.addListener((obj, oldSeleccion, newSeleccion) -> {
					if (newSeleccion != null) {
						Clientes cl = tblTablaCliente.getSelectionModel().getSelectedItem();
						txtNombreFactVD.setText(cl.getNombre());
						txtApellidoFactVD.setText(cl.getApellidoPaterno());
						factura.setCliente(cl);

					}
				});


	}

	private void limpiar() {
		this.txtReferrenciaFacturaVD.setText("");
		this.txtFechaNuevaFactVD.setValue(null);
		this.txtClienteBuscar.setText("");
		this.txtNombreFactVD.setText("");
		this.txtApellidoFactVD.setText("");
	}
}
