package fes.aragon.controlador;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.TextField;
import fes.aragon.modelo.Clientes;
import fes.aragon.modelo.Productos;
import fes.aragon.mysql.Conexion;
import javafx.event.ActionEvent;

public class NuevoProductoController {
	@FXML
	private TextField txtNombreProducto;
	@FXML
	private TextField txtPrecioProducto;
	@FXML
	private Productos producto = null;
	// Event Listener on Button.onAction
	@FXML
	public void accionGruardarProd(ActionEvent event) {
		// TODO Autogenerated
		if (producto == null) {
			producto = new Productos();
		}
		if (validarProd()) {
			Alert alerta = new Alert(Alert.AlertType.INFORMATION);
			if(producto.getId_productos()==null) {
				almacenarProd();
				alerta.setContentText("Producto Alamacenado Exitosamente");
				limpiarProd();
			}else {
				modificarProd();
				alerta.setContentText("Producto Modificado Exitosamente");
			}
			
			alerta.setHeaderText(null);
			
			alerta.showAndWait();
		}

	}
	// Event Listener on Button.onAction
	@FXML
	public void acciomLimpiarProd(ActionEvent event) {
		// TODO Autogenerated
		this.limpiarProd();
	}
	
	private void almacenarProd() {
		try {
			Conexion cnn = new Conexion();
			producto.setNombre_productos(txtNombreProducto.getText());
			producto.setPrecio_productos(Double.parseDouble(txtPrecioProducto.getText()));
			cnn.almacenarProductos(producto);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			Alert alerta = new Alert(Alert.AlertType.INFORMATION);
			alerta.setHeaderText(null);
			alerta.setContentText("Error, ocurrio un problema");
			alerta.showAndWait();
			e.printStackTrace();
		}
	}
	
	private void modificarProd() {
		try {
			Conexion cnn = new Conexion();
			producto.setNombre_productos(txtNombreProducto.getText());
			producto.setPrecio_productos(Double.parseDouble(txtPrecioProducto.getText()));
			cnn.modificarProductos(producto);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			Alert alerta = new Alert(Alert.AlertType.INFORMATION);
			alerta.setHeaderText(null);
			alerta.setContentText("Error, ocurrio un problema");
			alerta.showAndWait();
			e.printStackTrace();
		}
	}
	

	private void limpiarProd() {
		this.txtNombreProducto.setText("");
		this.txtPrecioProducto.setText("");
	}

	private boolean validarProd() {
		boolean validos = true;
		if (this.txtNombreProducto.getText().isEmpty() || this.txtNombreProducto.getText().regionMatches(0, "", 0, 1)) {
			validos = false;
		}
		if (this.txtPrecioProducto.getText().isEmpty()
				|| this.txtPrecioProducto.getText().regionMatches(0, "", 0, 1)) {
			validos = false;
		}
		return validos;
	}

	public void modificarProductos(Productos producto) {
		this.producto= producto;
		this.txtNombreProducto.setText(producto.getNombre_productos());
		this.txtPrecioProducto.setText(Double.toString(producto.getPrecio_productos()));

	}
	
}
