package fes.aragon.controlador;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.TextField;

import java.sql.SQLException;

import fes.aragon.modelo.Clientes;
import fes.aragon.mysql.Conexion;
import javafx.event.ActionEvent;

public class NuevoUsuarioController {
	@FXML
	private TextField txtNombre;
	@FXML
	private TextField txtApellidoPaterno;

	private Clientes cliente = null;

	// Event Listener on Button.onAction
	@FXML
	public void acciomLimpiar(ActionEvent event) {
		// TODO Autogenerated
		this.limpiar();
	}

	// Event Listener on Button.onAction
	@FXML
	public void accionGruardar(ActionEvent event) {
		// TODO Autogenerated
		if (cliente == null) {
			cliente = new Clientes();
		}
		if (validar()) {
			Alert alerta = new Alert(Alert.AlertType.INFORMATION);
			if(cliente.getIdC()==null) {
				almacenar();
				alerta.setContentText("Cliente Alamacenado Exitosamente");
				limpiar();
			}else {
				modificar();
				alerta.setContentText("Cliente Modificado Exitosamente");
			}
			
			alerta.setHeaderText(null);
			
			alerta.showAndWait();
		}

	}

	private void almacenar() {
		try {
			Conexion cnn = new Conexion();
			cliente.setNombre(txtNombre.getText());
			cliente.setApellidoPaterno(txtApellidoPaterno.getText());
			cnn.almacenarClientes(cliente);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			Alert alerta = new Alert(Alert.AlertType.INFORMATION);
			alerta.setHeaderText(null);
			alerta.setContentText("Error, ocurrio un problema");
			alerta.showAndWait();
			e.printStackTrace();
		}
	}
	
	private void modificar() {
		try {
			Conexion cnn = new Conexion();
			cliente.setNombre(txtNombre.getText());
			cliente.setApellidoPaterno(txtApellidoPaterno.getText());
			cnn.modificarClientes(cliente);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			Alert alerta = new Alert(Alert.AlertType.INFORMATION);
			alerta.setHeaderText(null);
			alerta.setContentText("Error, ocurrio un problema");
			alerta.showAndWait();
			e.printStackTrace();
		}
	}
	

	private void limpiar() {
		this.txtNombre.setText("");
		this.txtApellidoPaterno.setText("");
	}

	private boolean validar() {
		boolean validos = true;
		if (this.txtNombre.getText().isEmpty() || this.txtNombre.getText().regionMatches(0, "", 0, 1)) {
			validos = false;
		}
		if (this.txtApellidoPaterno.getText().isEmpty()
				|| this.txtApellidoPaterno.getText().regionMatches(0, "", 0, 1)) {
			validos = false;
		}
		return validos;
	}

	public void modificarCliente(Clientes cliente) {
		this.cliente = cliente;
		this.txtNombre.setText(cliente.getNombre());
		this.txtApellidoPaterno.setText(cliente.getApellidoPaterno());

	}

}
